### ISSUE TITLE
Why is generate_actions / execute_actions so slow?

### ISSUE THREAD

**Issue by AB-Athene** [fumitoh/modelx#169]
I have a model, which runs in 2 seconds for a subset of input file and 7 seconds for the full set. When I use subset to `generate_actions`, it takes 15 seconds. When I use full set to `execute_actions`, it takes 31 seconds. Why is it so much slower?

**Comment by fumitoh** [comment]
I think the reason why `generate_actions` is slow is because, when generating actions, formula execution is traced. Everytime a formula is executed with certain arguments, the timing of entering into and exiting from the formula is logged. This is making the execution solwer.

For `execute_action`, there're are 2 reasons. First, "value paste" operations are inserted at certain interval. Second,  garbage collection (freeing the memory for objects that are no longer needed thanks to "value paste") is performed at the end of each calc-paste-clear loop. I think the second reason is mostly the cause of slowing down the execution.

**Comment by AB-Athene** [comment]
Clear, thank you for the quick response
