### ISSUE TITLE
Ref/float = np.inf

### ISSUE THREAD

**Issue by HunterPxG** [fumitoh/modelx#62]
Hi, I have just started using modelx, and it seems that modelx does not allow to read models with reference equal to np.inf, the model can be used, but can not be read from a zip file. The solution I have found is store the reference like a np.array with a only element which is np.inf.

**Comment by fumitoh** [comment]
Thanks @HunterPxG  for the report.

In short, this is a bug, and will be fixed by the next release. The best way to get around the bug is to assing `np`, not `np.inf` to a Reference.

In more details, here are types of objects that can be assinged to References.

- `bool`, `int`, `float`, `str` objects (`np.inf` is of type `float`)
- Third-party modules, such as `numpy` and `pandas`.
- Other [pickleable ](https://docs.python.org/3/library/pickle.html)objects

Object that cannot be pickeled should not be directly assinged to References.
